spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
fileRepositoryFolder: D:\Develhope\SpringBoot_Develhope_Ex\Ex_22\FileRepository